config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  get 'articles', to: 'articles#index'
  get 'articles/new', to: 'articles#new'
  post 'articles/form', to: 'articles#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
# app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
      @articles = Article.all
    end
  
    def new
    end
  
    def create
      Article.create(
        title: params[:title],
        content: params[:content],
        published: params[:published]
      )
      redirect_to articles_path
    end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= link_to "New Article", articles_new_path %>
<% @articles.each do |article| %>
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>
  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>
  <p>
    <strong>Published:</strong>
    <%= article.published %>
  </p>
  <hr>
<% end %>

app/views/articles/new.html.erb
<!-- app/views/articles/new.html.erb -->
<h1>Crear un nuevo artículo</h1>

<%= form_with url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.label :published %><br>
    <%= form.check_box :published %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M8A03</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>